### ISSUE TITLE
Export to exe or dmg 

### ISSUE THREAD

**Issue by Zumbalamambo** [royabouhamad/TensorFlow-Image-Identifier#1]
How do I export the final application to exe or dmg file?

**Comment by royabouhamad** [comment]
I've been trying to find a way to do this myself but so far with no success. If you have some idea help would be appreciated.

**Comment by Zumbalamambo** [comment]
may be you can use pyinstaller

**Comment by royabouhamad** [comment]
Hi,
I don't think its worth exporting the final application to a dmg or exe as the dependencies I have used keep throwing errors at me when I try to use pyinstaller, cx_freeze and py2app. For this reason, I have included a requirements.txt file which can be used with pip on your computer to download the required dependencies.
